[package]
name = "java-highlight-nvim"
version = "0.1.0"
authors = ["LoadingBG <troyankru@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
lazy_static = "*"
